name: Test workload

on:
  workflow_dispatch:

jobs:
  buildonlatest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest,macos-15-intel,  macos-latest,ubuntu-22.04-arm,windows-11-arm]    
    
    steps:
    - uses: actions/checkout@v6

    - uses: gowridurgad/setup-dotnet@workloads-input
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          9.0.x
        workloads: wasm-tools, aspnet, grpc
          

  
