name: Test powershell on container

on:
  push:
  
jobs:
  test-proxy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/actions/test-ubuntu-git:main.20240221.114913.703z
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
      http_proxy: http://squid-proxy:3128
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check if PowerShell is installed
        run: |
          if command -v pwsh >/dev/null 2>&1; then
            echo "PowerShell is already installed"
            pwsh --version
          else
            echo "PowerShell is NOT installed"
          fi
