name: Version Test 


on:
  workflow_dispatch:

 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: HarithaVattikuti/setup-dotnet@copilot/add-workloads-parameter
        with:
          dotnet-version: '8.0.x'
          workloads: wasm-tools
          cache: true

  Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: HarithaVattikuti/setup-dotnet@copilot/add-workloads-parameter
        with:
          workloads: wasm-tools
          cache: true
