name: Version Test 


on:
  workflow_dispatch:

 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: gowridurgad/setup-dotnet@workload-input
        with:
          dotnet-version: '8.0.x'
          workloads: wasm-tools

  Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: gowridurgad/setup-dotnet@workload-input
        with:
          workloads: wasm-tools
